<a href="https://colab.research.google.com/github/mxrixA/Gomycode/blob/main/Checkpoint_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Exercice 01
listt=[]
for x in range(2000,3201):
  if x%7 ==0 and x%5 > 0:
    listt.append(x)
print(listt)
    
  
    


[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [ ]:
#Exercice 02
x=int(input())
fact=x
for n in range(1,x,1):
  y=x-n
  fact=fact*y
print(fact)  


5
120


In [ ]:
#Exercice 03
n=7
y={1:1}
for i in range (1,n+1):
  y[i]=i*i
print(y)


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49}


In [ ]:
#Exercice 04
x="kegjkdggo"
for n in x: 
  

SyntaxError: ignored

In [ ]:
#Exercice 05
import numpy as np
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
list1=array.tolist()
print(list1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
#Exercice 06
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([7,8,9])
data = np.array([arr1,arr2])
covMatrix = np.cov(data,bias=True)
print (covMatrix)

[[0.66666667 0.66666667]
 [0.66666667 0.66666667]]


In [21]:
#Exercice07
import numpy as np
H = 30
C = 50
D1, D2, D3 = [int(x) for x in input("Enter three value: ").split(",")]
Q1 = np.sqrt((2 * C * D1)/H)
Q2 = np.sqrt((2 * C * D2)/H)
Q3 = np.sqrt((2 * C * D3)/H)
z=(list((Q1,Q2,Q3)))
for i in range(0, len(z)):
    z[i] = round(z[i])
z




Enter three value: 5,9,55


[4, 5, 14]